# Generated by Django 3.1.6 on 2021-02-02 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appetite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorUser',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='donors',
            name='id',
        ),
        migrations.AddField(
            model_name='donors',
            name='day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donors',
            name='email',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donors',
            name='phoneNo',
            field=models.CharField(default=None, max_length=11, unique=True),
        ),
    ]
