# Generated by Django 3.1.6 on 2021-02-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=100)),
                ('phoneNo', models.CharField(default=None, max_length=11)),
                ('foodType', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(default=None, max_length=100)),
                ('region', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
