# Generated by Django 3.1.6 on 2021-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetite', '0003_auto_20210202_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donors',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='donors',
            name='phoneNo',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
