# Generated by Django 3.2.9 on 2021-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetite', '0004_auto_20210202_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(default=None, max_length=11)),
                ('address', models.CharField(default=None, max_length=100)),
                ('region', models.CharField(default=None, max_length=30)),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
